### ISSUE TITLE
Some traces are not correctly decoded

### ISSUE THREAD

**Issue by Airtnp** [hase-project/hase#23]
sanity_check_order error:
    Traceback (most recent call last):
    File "./bin/hase", line 11, in <module>
        main()
    File "/home/lrxiao/hase/hase/__init__.py", line 16, in main
        return args.func(args)
    File "/home/lrxiao/hase/hase/cli.py", line 59, in lazy_import_replay_command
        return replay_command(args)
    File "/home/lrxiao/hase/hase/replay.py", line 135, in replay_command
        with replay_trace(args.report) as rt:
    File "/home/lrxiao/hase/hase/replay.py", line 68, in __enter__
        self.prepare_tracer()
    File "/home/lrxiao/hase/hase/replay.py", line 85, in prepare_tracer
        trace = decode_trace(manifest, coredump.mappings, str(vdso_x64), str(binaries))
    File "/home/lrxiao/hase/hase/replay.py", line 55, in decode_trace
        vdso_x64=vdso_x64,
    File "/home/lrxiao/hase/hase/pt/decode.py", line 378, in decode
        sanity_check_order(instructions)
    File "/home/lrxiao/hase/hase/pt/decode.py", line 141, in sanity_check_order
        assert return_ip == instruction.ip
    AssertionError
 
 
cannot_add_shared_object error:
    Traceback (most recent call last):
    File "./bin/hase", line 11, in <module>
        main()
    File "/home/lrxiao/hase/hase/__init__.py", line 16, in main
        return args.func(args)
    File "/home/lrxiao/hase/hase/cli.py", line 59, in lazy_import_replay_command
        return replay_command(args)
    File "/home/lrxiao/hase/hase/replay.py", line 135, in replay_command
        with replay_trace(args.report) as rt:
    File "/home/lrxiao/hase/hase/replay.py", line 68, in __enter__
        self.prepare_tracer()
    File "/home/lrxiao/hase/hase/replay.py", line 85, in prepare_tracer
        trace = decode_trace(manifest, coredump.mappings, str(vdso_x64), str(binaries))
    File "/home/lrxiao/hase/hase/replay.py", line 55, in decode_trace
        vdso_x64=vdso_x64,
    File "/home/lrxiao/hase/hase/pt/decode.py", line 368, in decode
        shared_objects=shared_objects,
    hase.errors.PtError: cannot add shared object /tmp/tmp1mi26bwk/binaries/run/nscd/dbbVEQzG (deleted) to instruction image: invalid argument

sanity_check_order: file-1, tcpdump-144
cannot_add_shared_object: tcpdump-72

**Comment by Mic92** [comment]
After that it returns results for all recorded traces: https://github.com/hase-project/hase/pull/28

**Comment by Airtnp** [comment]
Have you tried replaying error traces?

**Comment by Mic92** [comment]
What do you mean by error traces?

**Comment by Airtnp** [comment]
file-1, tcpdump-144, tcpdump-72
