### ISSUE TITLE
Exception: target of reg_concrete is symbolic!

### ISSUE THREAD

**Issue by Mic92** [hase-project/hase#54]
```
hase replay recordings/file-6-b6e8437.tar.gz failed
Traceback (most recent call last):
  File "../bug-db/bin/bugdb-replay", line 49, in process_trace
    hase.main(["hase", "replay", trace])
  File "/local/incoop/hase/hase/__init__.py", line 14, in main
    return args.func(args)
  File "/local/incoop/hase/hase/cli.py", line 56, in lazy_import_replay_command
    return replay_command(args)
  File "/local/incoop/hase/hase/replay.py", line 140, in replay_command
    states.major_states[-1].simstate.reg_concrete("rsp")
  File "/local/incoop/hase/.direnv/python-3.6.6/lib/python3.6/site-packages/angr/sim_state.py", line 593, in reg_concrete
    raise SimValueError("target of reg_concrete is symbolic!")
```

```
hase replay recordings/file-2-4a51454.tar.gz failed
Traceback (most recent call last):
  File "../bug-db/bin/bugdb-replay", line 49, in process_trace
    hase.main(["hase", "replay", trace])
  File "/local/incoop/hase/hase/__init__.py", line 14, in main
    return args.func(args)
  File "/local/incoop/hase/hase/cli.py", line 56, in lazy_import_replay_command
    return replay_command(args)
  File "/local/incoop/hase/hase/replay.py", line 140, in replay_command
    states.major_states[-1].simstate.reg_concrete("rsp")
  File "/local/incoop/hase/.direnv/python-3.6.6/lib/python3.6/site-packages/angr/sim_state.py", line 593, in reg_concrete
    raise SimValueError("target of reg_concrete is symbolic!")
```

```
hase replay recordings/jasper-13-b702259.tar.gz failed
Traceback (most recent call last):
  File "../bug-db/bin/bugdb-replay", line 49, in process_trace
    hase.main(["hase", "replay", trace])
  File "/local/incoop/hase/hase/__init__.py", line 14, in main
    return args.func(args)
  File "/local/incoop/hase/hase/cli.py", line 56, in lazy_import_replay_command
    return replay_command(args)
  File "/local/incoop/hase/hase/replay.py", line 140, in replay_command
    states.major_states[-1].simstate.reg_concrete("rsp")
  File "/local/incoop/hase/.direnv/python-3.6.6/lib/python3.6/site-packages/angr/sim_state.py", line 593, in reg_concrete
    raise SimValueError("target of reg_concrete is symbolic!")
angr.errors.SimValueError: target of reg_concrete is symbolic!
```

**Comment by Airtnp** [comment]
A new variant on making rsp symbolic... Will have a look.
