### ISSUE TITLE
hase: cannot return from a system call loopy

### ISSUE THREAD

**Issue by Mic92** [hase-project/hase#7]
Currently fails to replay our integration test: https://github.com/hase-project/hase/blob/master/tests/test_record.py

```
look for jump: 0x4000e8 -> 0x4000ec
                  se The name state.se is deprecated; please use state.solver.
look for jump: 0x4000ec -> 0x4000f0
look for jump: 0x4000f0 -> 0x4000f2
look for jump: 0x4000f2 -> 0x4000f9
look for jump: 0x4000f9 -> 0x400100
look for jump: 0x400100 -> 0x400107
look for jump: 0x400107 -> 0x40010e
look for jump: 0x40010e -> 0x400110
[<SimState @ 0x300016b>] <SimState @ 0x300016b> <Instruction[ptic_other] @ 400110>
E
======================================================================
ERROR: Full integration test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joerg/git/hase/.direnv/python-3.6.6/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/mnt/data/joerg/hase/tests/test_record.py", line 82, in test_record_command
    states = main(["hase", "replay", str(archives[0])])
  File "/mnt/data/joerg/hase/hase/__init__.py", line 16, in main
    return args.func(args)
  File "/mnt/data/joerg/hase/hase/cli.py", line 59, in lazy_import_replay_command
    return replay_command(args)
  File "/mnt/data/joerg/hase/hase/replay.py", line 136, in replay_command
    return rt.run()
  File "/mnt/data/joerg/hase/hase/replay.py", line 102, in run
    return self.tracer.run()
  File "/mnt/data/joerg/hase/hase/symbex/tracer.py", line 932, in run
    old_simstate, new_simstate = self.execute(simstate, previous_instruction, instruction, cnt)
  File "/mnt/data/joerg/hase/hase/symbex/tracer.py", line 869, in execute
    raise HaseError("Unable to continue")
hase.errors.HaseError: Unable to continue
```

It fails at this instruction: 0x40010e -> 0x400110

which is the system call from https://github.com/hase-project/hase/blob/49ef94b8d3627c4134e939e2f6fe16f4ed3e2d7e/tests/src/loopy/loopy.S#L22
to https://github.com/hase-project/hase/blob/49ef94b8d3627c4134e939e2f6fe16f4ed3e2d7e/tests/src/loopy/loopy.S#L25

The archive in question is attached:

[loopy-20181109T183320.tar.gz](https://github.com/hase-project/hase/files/2567095/loopy-20181109T183320.tar.gz)

cc @Airtnp

**Comment by Mic92** [comment]
fixed in https://github.com/hase-project/hase/commit/9c526f2c526ab4bb0a7a7737c24e9a4ce196535a
